version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: daily_challenges_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: daily_challenges
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - testnet

networks:
  testnet:
    external: true
    name: testnet
